# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
# Altered by Shane Mill (shane.mill@noaa.gov) for the purposes of creating
# an NWS implementation of OGC API - Processes
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5400
    url: http://localhost:5400
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    languages:
        # First language is the default language
        - en-US
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
        description:
            en: pygeoapi provides an API to geospatial data
        keywords:
            en:
                - geospatial
                - data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: NOAA - National Weather Service
        url: https://vlab.noaa.gov/web/mdl/data-api
    contact:
        name: Mill, Shane
        position: Application Developer
        address: SSMC2
        city: Silver Spring
        stateorprovince: MD
        postalcode: 20910
        country: USA
        email: shane.mill@noaa.gov
        role: pointOfContact

resources:
    canada-metadata:
        type: collection
        title:
            en: Open Canada sample data
            fr: Exemple de donn\u00e9es Canada Ouvert
        description:
            en: Sample metadata records from open.canada.ca
            fr: Exemples d'enregistrements de m\u00e9tadonn\u00e9es sur ouvert.canada.ca
        keywords:
            en:
                - canada
                - open data
            fr:
                - canada
                - donn\u00e9es ouvertes
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://open.canada.ca/en/open-data
              hreflang: en-CA
            - type: text/html
              rel: alternate
              title: informations
              href: https://ouvert.canada.ca/fr/donnees-ouvertes
              hreflang: fr-CA
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: record
              name: TinyDBCatalogue
              data: tests/data/open.canada.ca/sample-records.tinydb
              id_field: externalId
              time_field: recordCreated
              title_field: title


    noaa-nws-mdl-metadata:
        type: collection
        title:
            en: NOAA/NWS/MDL EDR Prototype Metadata
        description:
            en: Begin prototyping EDR metadata for OGC-API Records
        keywords:
            en:
                - nws
                - open data
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://data-api-c.mdl.nws.noaa.gov/OGC-EDR-API
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: record
              name: TinyDBCatalogue
              data: metadata_loader/db.json
              id_field: externalId
              time_field: recordCreated
              title_field: title



